### ISSUE TITLE
support delete events?

### ISSUE THREAD

**Issue by ePaul** [zalando-incubator/tarbela-producer-spring-boot-starter#6]
EventLogWriter has two methods: `fireCreateEvent` and `fireUpdateEvent`.
Could we also have `fireDeleteEvent`?

(And possibly `fireSnapshotEvent`, though this is maybe not needed because we have the API for that.)

**Comment by qlibin** [comment]
We'll fix it

Thank you for the report @ePaul!

**Comment by raphaelbauer** [comment]
Just one quick note: 
Not sure when we will have time for that so if you need the methods urgently feel free to create PR for that :) This will speed things up :) Thanks!

**Comment by qlibin** [comment]
Please review #7 PR and provide some feedback

**Comment by qlibin** [comment]
fixed here #7
